# Generated by Django 2.0.8 on 2019-07-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190727_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
